services:
  - type: web
    name: amazon-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: amazon-postgres
          property: connectionString
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        fromDatabase:
          name: amazon-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: amazon-postgres
          property: password
      - key: DB_NAME
        fromDatabase:
          name: amazon-postgres
          property: database

databases:
  - name: amazon-postgres
    databaseName: ${DB_NAME}
    user: ${DB_USER}
    plan: free
